# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-19 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Screlation',
            fields=[
                ('counterno', models.CharField(db_column='CounterNo', max_length=100, verbose_name='窗口编号')),
                ('serviceno', models.CharField(db_column='ServiceNo', max_length=100, verbose_name='业务编号')),
                ('servicename', models.CharField(blank=True, db_column='ServiceName', max_length=500, null=True, verbose_name='业务名称')),
                ('serviceid', models.IntegerField(db_column='ServiceId', primary_key=True, serialize=False, verbose_name='业务排序号')),
            ],
            options={
                'verbose_name_plural': '业务与窗口对应关系',
                'db_table': 'screlation',
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='screlation',
            unique_together=set([('counterno', 'serviceno', 'serviceid')]),
        ),
    ]
