# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-18 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wait', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('serviceno', models.IntegerField(db_column='ServiceNo', primary_key=True, serialize=False)),
                ('servicetype', models.CharField(blank=True, db_column='ServiceType', max_length=20, null=True)),
                ('digitlength', models.IntegerField(blank=True, db_column='DigitLength', null=True)),
                ('servicename', models.CharField(blank=True, db_column='ServiceName', max_length=128, null=True)),
                ('workflowtext', models.CharField(blank=True, db_column='WorkflowText', max_length=756, null=True)),
                ('workflowcounter', models.CharField(blank=True, db_column='WorkflowCounter', max_length=512, null=True)),
                ('buttonleft', models.IntegerField(blank=True, db_column='ButtonLeft', null=True)),
                ('buttontop', models.IntegerField(blank=True, db_column='ButtonTop', null=True)),
                ('buttonwidth', models.IntegerField(blank=True, db_column='ButtonWidth', null=True)),
                ('buttonheight', models.IntegerField(blank=True, db_column='ButtonHeight', null=True)),
                ('locationtemplate', models.IntegerField(blank=True, db_column='LocationTemplate', null=True)),
                ('buttonbg', models.TextField(blank=True, db_column='ButtonBG', null=True)),
                ('buttonshowtext', models.IntegerField(blank=True, db_column='ButtonShowText', null=True)),
                ('tickettemplate', models.TextField(blank=True, db_column='TicketTemplate', null=True)),
                ('amlimit', models.IntegerField(blank=True, db_column='AMLimit', null=True)),
                ('amstarttime', models.DateTimeField(blank=True, db_column='AMStartTime', null=True)),
                ('amendtime', models.DateTimeField(blank=True, db_column='AMEndTime', null=True)),
                ('amtotal', models.IntegerField(blank=True, db_column='AMTotal', null=True)),
                ('pmlimit', models.IntegerField(blank=True, db_column='PMLimit', null=True)),
                ('pmstarttime', models.DateTimeField(blank=True, db_column='PMStartTime', null=True)),
                ('pmendtime', models.DateTimeField(blank=True, db_column='PMEndTime', null=True)),
                ('pmtotal', models.IntegerField(blank=True, db_column='PMTotal', null=True)),
                ('printpause', models.IntegerField(blank=True, db_column='PrintPause', null=True)),
                ('fontstyle', models.CharField(blank=True, db_column='FontStyle', max_length=128, null=True)),
                ('fontcolor', models.CharField(blank=True, db_column='FontColor', max_length=32, null=True)),
                ('parentid', models.IntegerField(blank=True, db_column='ParentID', null=True)),
                ('havechild', models.IntegerField(blank=True, db_column='HaveChild', null=True)),
                ('field_mask_to_v2', models.DateTimeField(blank=True, db_column='_MASK_TO_V2', null=True)),
            ],
            options={
                'db_table': 'service',
                'managed': False,
            },
        ),
    ]
