# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-02-20 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wait', '0002_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticketno', models.CharField(db_column='TicketNo', max_length=32, primary_key=True, serialize=False)),
                ('serviceno', models.IntegerField(blank=True, db_column='ServiceNo', null=True)),
                ('printtime', models.DateTimeField(db_column='PrintTime')),
                ('queuetime', models.DateTimeField(blank=True, db_column='QueueTime', null=True)),
                ('starttime', models.DateTimeField(blank=True, db_column='StartTime', null=True)),
                ('finishedtime', models.DateTimeField(blank=True, db_column='FinishedTime', null=True)),
                ('cometime', models.CharField(blank=True, db_column='ComeTime', max_length=512, null=True)),
                ('processedtime', models.CharField(blank=True, db_column='ProcessedTime', max_length=512, null=True)),
                ('processedcounter', models.CharField(blank=True, db_column='ProcessedCounter', max_length=256, null=True)),
                ('processedstaffid', models.CharField(blank=True, db_column='ProcessedStaffID', max_length=512, null=True)),
                ('processingstatus', models.IntegerField(blank=True, db_column='ProcessingStatus', null=True)),
                ('lastcounter', models.IntegerField(blank=True, db_column='LastCounter', null=True)),
                ('processing', models.IntegerField(blank=True, db_column='Processing', null=True)),
                ('nextworkflow', models.CharField(blank=True, db_column='NextWorkflow', max_length=512, null=True)),
                ('nextcounter', models.CharField(blank=True, db_column='NextCounter', max_length=256, null=True)),
                ('priority', models.IntegerField(blank=True, db_column='Priority', null=True)),
                ('paused', models.IntegerField(blank=True, db_column='Paused', null=True)),
                ('customerrating', models.CharField(blank=True, db_column='CustomerRating', max_length=256, null=True)),
                ('delaybytime', models.IntegerField(blank=True, db_column='DelayByTime', null=True)),
                ('delaywayvalue', models.IntegerField(blank=True, db_column='DelayWayValue', null=True)),
                ('delaystarttime', models.DateTimeField(blank=True, db_column='DelayStartTime', null=True)),
                ('delayticketspassed', models.IntegerField(blank=True, db_column='DelayTicketsPassed', null=True)),
                ('parameters', models.CharField(blank=True, db_column='Parameters', max_length=256, null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=32, null=True)),
                ('regtime', models.CharField(blank=True, db_column='RegTime', max_length=16, null=True)),
                ('deptname', models.CharField(blank=True, db_column='DeptName', max_length=32, null=True)),
                ('reexam', models.IntegerField(blank=True, db_column='Reexam', null=True)),
                ('mobilephone', models.CharField(blank=True, db_column='MobilePhone', max_length=16, null=True)),
                ('smsresult', models.IntegerField(blank=True, db_column='SmsResult', null=True)),
                ('smstimes', models.IntegerField(blank=True, db_column='SmsTimes', null=True)),
                ('reservationstarttime', models.DateTimeField(blank=True, db_column='ReservationStartTime', null=True)),
                ('reservationendtime', models.DateTimeField(blank=True, db_column='ReservationEndTime', null=True)),
                ('reservationno', models.CharField(blank=True, db_column='ReservationNo', max_length=32, null=True)),
                ('field_mask_to_v2', models.DateTimeField(blank=True, db_column='_MASK_TO_V2', null=True)),
            ],
            options={
                'db_table': 'ticket',
                'managed': False,
            },
        ),
    ]
