# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-05 01:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wait', '0003_ticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'get_latest_by': 'printtime', 'managed': False},
        ),
    ]
