# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-01-31 09:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='zzJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daihao', models.CharField(max_length=255, verbose_name='岗位代号')),
                ('name', models.CharField(max_length=255, verbose_name='招考岗位')),
                ('count', models.CharField(max_length=5, verbose_name='招聘人数')),
                ('education', models.CharField(max_length=255, verbose_name='学历要求')),
                ('major', models.CharField(max_length=512, verbose_name='专业要求')),
                ('other', models.TextField(verbose_name='其他要求')),
                ('note', models.TextField(verbose_name='备注')),
                ('state', models.CharField(max_length=63, verbose_name='状态')),
                ('outtime', models.DateTimeField(blank=True, null=True, verbose_name='到期时间')),
                ('hold0', models.CharField(blank=True, default='保留', max_length=255, null=True, verbose_name='最低年龄限制条件')),
                ('hold1', models.CharField(blank=True, default='保留', max_length=255, null=True, verbose_name='保留字段')),
                ('hold2', models.CharField(blank=True, default='保留', max_length=255, null=True, verbose_name='保留字段')),
                ('hold3', models.CharField(blank=True, default='保留', max_length=255, null=True, verbose_name='保留字段')),
            ],
            options={
                'verbose_name': '招聘岗位',
                'verbose_name_plural': '招聘岗位',
            },
        ),
        migrations.CreateModel(
            name='zzJoinJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='待审核', max_length=63, verbose_name='状态')),
                ('sweat', models.CharField(default='待定', max_length=255, verbose_name='考试座位')),
                ('score', models.CharField(default='待定', max_length=10, verbose_name='考试分数')),
                ('process', models.CharField(default='笔试', max_length=52, verbose_name='招聘进度')),
                ('note', models.CharField(default='无', max_length=255, verbose_name='备注')),
                ('zkzh', models.CharField(default='XXXX******####', max_length=255, verbose_name='准考证号')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zzb.zzJob', verbose_name='招聘岗位')),
            ],
            options={
                'verbose_name': '报名单',
                'verbose_name_plural': '报名单',
            },
        ),
        migrations.CreateModel(
            name='zzNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('date_publish', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('user', models.CharField(max_length=255, verbose_name='发布人')),
                ('state', models.CharField(max_length=25, verbose_name='文章状态')),
            ],
            options={
                'verbose_name': '通知公告',
                'verbose_name_plural': '通知公告',
                'ordering': ['-date_publish'],
            },
        ),
        migrations.CreateModel(
            name='zzTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='招聘项目名称')),
                ('startbm', models.DateTimeField(default=datetime.datetime(2019, 1, 31, 9, 47, 1, 426571), verbose_name='开始报名时间')),
                ('endbm', models.DateTimeField(default=datetime.datetime(2019, 1, 31, 9, 47, 1, 426571), verbose_name='结束报名时间')),
                ('startdy', models.DateTimeField(default=datetime.datetime(2019, 1, 31, 9, 47, 1, 426571), verbose_name='开始打印时间')),
                ('enddy', models.DateTimeField(default=datetime.datetime(2019, 1, 31, 9, 47, 1, 426571), verbose_name='结束打印时间')),
                ('startbs', models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 31, 9, 47, 1, 426571), null=True, verbose_name='开始笔试时间')),
                ('endbs', models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 31, 9, 47, 1, 426571), null=True, verbose_name='结束笔试时间')),
                ('startcj', models.DateTimeField(default=datetime.datetime(2019, 1, 31, 9, 47, 1, 426571), verbose_name='开始查询时间')),
                ('endcj', models.DateTimeField(default=datetime.datetime(2019, 1, 31, 9, 47, 1, 426571), verbose_name='结束查询时间')),
                ('state', models.BooleanField(default=False, verbose_name='项目状态')),
            ],
            options={
                'verbose_name': '招聘项目时间流程',
                'verbose_name_plural': '招聘项目时间流程',
            },
        ),
        migrations.CreateModel(
            name='zzUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='用户名')),
                ('idcard', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='身份证')),
                ('phone', models.CharField(blank=True, default='', max_length=11, null=True, verbose_name='手机号码')),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='电子邮箱')),
                ('username', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='用户账号')),
                ('password', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='用户密码')),
                ('logo', models.ImageField(default='BUser/logo/人.png', upload_to='BUser/logo', verbose_name='用户头像')),
                ('power', models.IntegerField(default=0, verbose_name='权限系数')),
                ('hold0', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='预留字段0')),
                ('hold1', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='预留字段1')),
                ('hold2', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='预留字段2')),
                ('hold3', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='预留字段3')),
            ],
            options={
                'verbose_name': '用户记录',
                'verbose_name_plural': '用户记录',
            },
        ),
        migrations.CreateModel(
            name='zzUserExtend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='姓名')),
                ('sex', models.CharField(default='', max_length=10, verbose_name='性别')),
                ('minzu', models.CharField(default='', max_length=10, verbose_name='民族')),
                ('chusheng', models.CharField(default='', max_length=255, verbose_name='出生年月')),
                ('jiguan', models.CharField(default='', max_length=255, verbose_name='籍贯')),
                ('mianmao', models.CharField(default='', max_length=255, verbose_name='政治面貌')),
                ('huji', models.CharField(default='', max_length=255, verbose_name='现户籍地')),
                ('hunyin', models.CharField(default='', max_length=255, verbose_name='婚姻状况')),
                ('logo', models.ImageField(default='', max_length=255, upload_to='', verbose_name='彩照')),
                ('idcard', models.CharField(default='', max_length=255, verbose_name='身份证')),
                ('phone', models.CharField(default='', max_length=255, verbose_name='联系电话')),
                ('tongxun', models.CharField(default='', max_length=255, verbose_name='通讯地址')),
                ('youbian', models.CharField(default='', max_length=255, verbose_name='邮编')),
                ('xuexiao', models.CharField(default='', max_length=255, verbose_name='毕业院校')),
                ('biye', models.CharField(default='', max_length=255, verbose_name='毕业时间')),
                ('zhuanye', models.CharField(default='', max_length=255, verbose_name='所学专业')),
                ('xueli', models.CharField(default='', max_length=255, verbose_name='学历及学位')),
                ('waiyu', models.CharField(default='', max_length=255, verbose_name='外语水平')),
                ('jisuanji', models.CharField(default='', max_length=255, verbose_name='计算机水平')),
                ('danwei', models.CharField(default='', max_length=255, verbose_name='工作单位')),
                ('xingzhi', models.CharField(default='', max_length=255, verbose_name='单位性质')),
                ('luoshi', models.CharField(default='', max_length=255, verbose_name='裸视视力')),
                ('jiaozheng', models.CharField(default='', max_length=255, verbose_name='矫正视力')),
                ('shengao', models.CharField(default='', max_length=255, verbose_name='身高')),
                ('jishu', models.CharField(default='', max_length=255, verbose_name='专业技术资格')),
                ('zhiye1', models.CharField(default='', max_length=255, verbose_name='职业资格')),
                ('zhiye2', models.CharField(default='', max_length=255, verbose_name='执业资格')),
                ('daxue', models.TextField(default='', verbose_name='大学担任职务')),
                ('jingli', models.TextField(default='', verbose_name='学习、工作经历')),
                ('guanxi', models.TextField(default='', verbose_name='成员关系')),
                ('techang', models.TextField(default='', verbose_name='特长及突出业绩')),
                ('jiangfa', models.TextField(default='', verbose_name='奖罚情况')),
                ('shenhe', models.TextField(default='', verbose_name='审核意见')),
                ('beizhu', models.TextField(default='', verbose_name='备注')),
                ('note1', models.CharField(default='', max_length=255, verbose_name='保留字段1')),
                ('note2', models.CharField(default='', max_length=255, verbose_name='保留字段2')),
                ('note3', models.TextField(default='', verbose_name='保留字段3')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='zzb.zzUser', verbose_name='用户')),
            ],
            options={
                'verbose_name': '个人信息表',
                'verbose_name_plural': '个人信息表',
            },
        ),
        migrations.CreateModel(
            name='zzWechatUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=255, verbose_name='用户识别号')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='用户名')),
                ('idcard', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='身份证')),
                ('phone', models.CharField(blank=True, default='', max_length=11, null=True, verbose_name='手机号码')),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='电子邮箱')),
                ('power', models.IntegerField(default=0, verbose_name='权限系数')),
                ('logo', models.ImageField(default='BUser/logo/人.png', upload_to='BUser/logo', verbose_name='用户头像')),
                ('hold0', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='预留字段0')),
                ('hold1', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='预留字段1')),
                ('hold2', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='预留字段2')),
                ('hold3', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='预留字段3')),
            ],
            options={
                'verbose_name': '微信用户',
                'verbose_name_plural': '微信用户',
            },
        ),
        migrations.AddField(
            model_name='zzjoinjob',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='zzb.zzUserExtend', verbose_name='报考人员'),
        ),
    ]
