# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-19 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zzb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='zzTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='招聘项目名称')),
                ('startbm', models.DateTimeField(verbose_name='开始报名时间')),
                ('endbm', models.DateTimeField(verbose_name='结束报名时间')),
                ('startdy', models.DateTimeField(verbose_name='开始打印时间')),
                ('enddy', models.DateTimeField(verbose_name='结束打印时间')),
                ('startbs', models.DateTimeField(blank=True, null=True, verbose_name='开始笔试时间')),
                ('endbs', models.DateTimeField(blank=True, null=True, verbose_name='结束笔试时间')),
                ('startcj', models.DateTimeField(verbose_name='开始查询时间')),
                ('endcj', models.DateTimeField(verbose_name='结束查询时间')),
                ('state', models.BooleanField(default=False, verbose_name='项目状态')),
            ],
            options={
                'verbose_name': '招聘项目时间流程',
                'verbose_name_plural': '招聘项目时间流程',
            },
        ),
    ]
