# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-20 00:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zzb', '0002_zztime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zztime',
            name='endbm',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 20, 0, 7, 1, 403620), verbose_name='结束报名时间'),
        ),
        migrations.AlterField(
            model_name='zztime',
            name='startbm',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 20, 0, 7, 1, 403620), verbose_name='开始报名时间'),
        ),
        migrations.AlterField(
            model_name='zztime',
            name='startdy',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 20, 0, 7, 1, 403620), verbose_name='开始打印时间'),
        ),
    ]
