# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-22 15:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zzb', '0004_auto_20180620_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='zzjob',
            name='hold0',
            field=models.CharField(blank=True, default='保留', max_length=255, null=True, verbose_name='年龄限制条件'),
        ),
        migrations.AddField(
            model_name='zzjob',
            name='hold1',
            field=models.CharField(blank=True, default='保留', max_length=255, null=True, verbose_name='保留字段'),
        ),
        migrations.AddField(
            model_name='zzjob',
            name='hold2',
            field=models.CharField(blank=True, default='保留', max_length=255, null=True, verbose_name='保留字段'),
        ),
        migrations.AddField(
            model_name='zzjob',
            name='hold3',
            field=models.CharField(blank=True, default='保留', max_length=255, null=True, verbose_name='保留字段'),
        ),
        migrations.AlterField(
            model_name='zztime',
            name='endbm',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 22, 15, 21, 24, 942405), verbose_name='结束报名时间'),
        ),
        migrations.AlterField(
            model_name='zztime',
            name='endbs',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 22, 15, 21, 24, 942405), null=True, verbose_name='结束笔试时间'),
        ),
        migrations.AlterField(
            model_name='zztime',
            name='endcj',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 22, 15, 21, 24, 942405), verbose_name='结束查询时间'),
        ),
        migrations.AlterField(
            model_name='zztime',
            name='enddy',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 22, 15, 21, 24, 942405), verbose_name='结束打印时间'),
        ),
        migrations.AlterField(
            model_name='zztime',
            name='startbm',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 22, 15, 21, 24, 942405), verbose_name='开始报名时间'),
        ),
        migrations.AlterField(
            model_name='zztime',
            name='startbs',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 22, 15, 21, 24, 942405), null=True, verbose_name='开始笔试时间'),
        ),
        migrations.AlterField(
            model_name='zztime',
            name='startcj',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 22, 15, 21, 24, 942405), verbose_name='开始查询时间'),
        ),
        migrations.AlterField(
            model_name='zztime',
            name='startdy',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 22, 15, 21, 24, 942405), verbose_name='开始打印时间'),
        ),
    ]
