# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-07 04:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zzb', '0005_auto_20180622_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='zzjoinjob',
            name='zkzh',
            field=models.CharField(default='XXXX******####', max_length=255, verbose_name='准考证号'),
        ),
        migrations.AlterField(
            model_name='zzjob',
            name='hold0',
            field=models.CharField(blank=True, default='保留', max_length=255, null=True, verbose_name='最低年龄限制条件'),
        ),
        migrations.AlterField(
            model_name='zztime',
            name='endbm',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 7, 4, 29, 26, 330716), verbose_name='结束报名时间'),
        ),
        migrations.AlterField(
            model_name='zztime',
            name='endbs',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 7, 7, 4, 29, 26, 330716), null=True, verbose_name='结束笔试时间'),
        ),
        migrations.AlterField(
            model_name='zztime',
            name='endcj',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 7, 4, 29, 26, 330716), verbose_name='结束查询时间'),
        ),
        migrations.AlterField(
            model_name='zztime',
            name='enddy',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 7, 4, 29, 26, 330716), verbose_name='结束打印时间'),
        ),
        migrations.AlterField(
            model_name='zztime',
            name='startbm',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 7, 4, 29, 26, 330716), verbose_name='开始报名时间'),
        ),
        migrations.AlterField(
            model_name='zztime',
            name='startbs',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 7, 7, 4, 29, 26, 330716), null=True, verbose_name='开始笔试时间'),
        ),
        migrations.AlterField(
            model_name='zztime',
            name='startcj',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 7, 4, 29, 26, 330716), verbose_name='开始查询时间'),
        ),
        migrations.AlterField(
            model_name='zztime',
            name='startdy',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 7, 4, 29, 26, 330716), verbose_name='开始打印时间'),
        ),
    ]
