# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-18 16:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zzb', '0009_auto_20191017_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='zzBaseComfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='配置名称')),
                ('content', models.TextField(verbose_name='配置内容')),
                ('use', models.BooleanField(default=False, verbose_name='是否启动')),
                ('hold0', models.CharField(max_length=255, verbose_name='预留字段0')),
                ('hold1', models.CharField(max_length=255, verbose_name='预留字段1')),
            ],
            options={
                'verbose_name': '系统基础配置',
                'verbose_name_plural': '系统基础配置',
            },
        ),
        migrations.AlterField(
            model_name='zztime',
            name='endbm',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 18, 16, 44, 25, 126475), verbose_name='结束报名时间'),
        ),
        migrations.AlterField(
            model_name='zztime',
            name='endbs',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 18, 16, 44, 25, 126527), null=True, verbose_name='结束笔试时间'),
        ),
        migrations.AlterField(
            model_name='zztime',
            name='endcj',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 18, 16, 44, 25, 126551), verbose_name='结束查询时间'),
        ),
        migrations.AlterField(
            model_name='zztime',
            name='enddy',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 18, 16, 44, 25, 126502), verbose_name='结束打印时间'),
        ),
        migrations.AlterField(
            model_name='zztime',
            name='startbm',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 18, 16, 44, 25, 126450), verbose_name='开始报名时间'),
        ),
        migrations.AlterField(
            model_name='zztime',
            name='startbs',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 18, 16, 44, 25, 126514), null=True, verbose_name='开始笔试时间'),
        ),
        migrations.AlterField(
            model_name='zztime',
            name='startcj',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 18, 16, 44, 25, 126539), verbose_name='开始查询时间'),
        ),
        migrations.AlterField(
            model_name='zztime',
            name='startdy',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 18, 16, 44, 25, 126489), verbose_name='开始打印时间'),
        ),
    ]
