# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-19 20:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zzb', '0010_auto_20191018_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zzbasecomfig',
            name='hold0',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='预留字段0'),
        ),
        migrations.AlterField(
            model_name='zzbasecomfig',
            name='hold1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='预留字段1'),
        ),
        migrations.AlterField(
            model_name='zztime',
            name='endbm',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 19, 20, 19, 40, 334326), verbose_name='结束报名时间'),
        ),
        migrations.AlterField(
            model_name='zztime',
            name='endbs',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 19, 20, 19, 40, 334388), null=True, verbose_name='结束笔试时间'),
        ),
        migrations.AlterField(
            model_name='zztime',
            name='endcj',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 19, 20, 19, 40, 334416), verbose_name='结束查询时间'),
        ),
        migrations.AlterField(
            model_name='zztime',
            name='enddy',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 19, 20, 19, 40, 334358), verbose_name='结束打印时间'),
        ),
        migrations.AlterField(
            model_name='zztime',
            name='startbm',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 19, 20, 19, 40, 334300), verbose_name='开始报名时间'),
        ),
        migrations.AlterField(
            model_name='zztime',
            name='startbs',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 19, 20, 19, 40, 334373), null=True, verbose_name='开始笔试时间'),
        ),
        migrations.AlterField(
            model_name='zztime',
            name='startcj',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 19, 20, 19, 40, 334403), verbose_name='开始查询时间'),
        ),
        migrations.AlterField(
            model_name='zztime',
            name='startdy',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 19, 20, 19, 40, 334343), verbose_name='开始打印时间'),
        ),
    ]
